name: GitHub Action Badge Trigger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "🎉 Hello from GitHub Actions!"
